name: Walmart Scrape Automation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * * *'
    - cron: '0 16 * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: python scrape.py "https://www.walmart.com/ip/SAMSUNG" -o somenewoutput.json
      - name: Commit results
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add -A
            git commit -m 'Automation update'
            git push
          fi
