name: Walmart Scrape Automation

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/20 * * * *'
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pip install -r requirements.txt
      - run: python scrape.py "https://www.walmart.com/ip/SAMSUNG-27-Class-Curved-1920x1080-VGA-HDMI-60hz-4ms-AMD-Freesync-HD-LED-Monitor-LC27F396FHNXZA/117633165?athAsset=eyJhdGhjcGlkIjoiMTE3NjMzMTY1IiwiYXRoc3RpZCI6IkNTMDk4IiwiYXRocG9zYiI6IjYiLCJhdGhhbmNpZCI6Ikl0ZW1DYXJvdXNlbCIsImF0aHJrIjowLjB9&athena=true&adsRedirect=true -o output.json"
      - name: Commit results
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'
            git add -A
            git commit -m 'Automation update'
            git push
          fi
